name: 'Auto Assign Pull Request'
on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: gerardabello/auto-assign@v1.0.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          number-of-assignees: 1
          assignee-pool: |
            mushlih-almubarak